### ISSUE TITLE
Research possibilities to distribute the server along with the game

### ISSUE THREAD

**Issue by kjarosh** [Fruktus/QuadradiusR#213]
The server distributed with the game would be used to host ad-hoc sessions.

**Comment by Fruktus** [comment]
I'd personally check if we could use heroku, this is not exactly to distribute the server but would solve some of the current problems.
As for the distribution, we could bundle the server with portable python installation with all dependencies preinstalled.

**Comment by kjarosh** [comment]
Pyinstaller https://pyinstaller.org/en/stable/ could be the way. It can package the whole application into executables which do not require Python to be installed on the target system.

However, I can see several problems:
1. Windows and MacOS compatibility: pyinstaller supports both of them, but it does not support cross compilation. We are currently building our modules exclusively on Linux (even Windows and MacOS executables).
2. `glibc` compatibility: glibc is not packaged with the application, we would have to ensure that we build our application on systems with old enough version of glibc.

This is the command I used to build an executable:
```bash
pyinstaller -F -n quadradiusr_server --hidden-import aiosqlite src/quadradiusr_server/__main__.py
```
