### ISSUE TITLE
Error in stacktrace on connecting two players

### ISSUE THREAD

**Issue by Observer46** [Fruktus/QuadradiusR#256]
When connecting 2 players, stacktrace explodes on server. Probably related to #253. 

To replicate on #253:
- create user A
- create user B
- invite each other
- join the game (one player crashes and stacktrace is shown on server)

[log.txt](https://github.com/Fruktus/QuadradiusR/files/8674224/log.txt)

**Comment by kjarosh** [comment]
This error was caused by the server trying to broadcast game state diff to other player which was not connected at the time.
